repository: 

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

title: "Marlowe User Documentation"
image: "/assets/globus_square.png"
site_title: Marlowe User Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

#THIS IS JUST FOR DEV PREVIEW
#domain: saracook.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#url: https://saracook.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /docs.marlowe.stanford.edu/      # place folder name if the site is served in a subfolder

#PROD SETTINGS
#domain: docs.marlowe.stanford.edu
#url: https://docs.marlowe.stanford.edu
#baseurl: /
owner:
  # The owner name must be provided.
  name: "Stanford Research Computing"

# These defaults apply when a matching page variable is not set.
# NOTE: You should set most of these in page-specific YAML.
defaults:
  -
    scope:
      path: ""
    values:
      title: "Page Title"
      description: null
      layout: default
      sitemap: true
      toc: true
      sidebar-box: null
      social:
        # The title to use when Twitter et al show a link to your site.
        # When set to null, Jekyll will generate the string
        # "PAGE_TITLE â€” SITE_TITLE".
        title: Marlowe at Stanford

        # The image to show when someone expands a Twitter post with your page
        # linked.  This should be a path relative to your site root.  If not
        # set, your site's image will be used instead.
        image: null

# These are Jekyll plugins that we enable.
# NOTE: We can only use plugins that GitHub makes available.
# The list is here: https://pages.github.com/versions/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-titles-from-headings

# This is a list of files that should be excluded from the _site directory.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
#  - jekyll-theme-stanford-lagunita.gemspec
  - vendor

# These are some Jekyll defaults, which should be left alone.
timezone: America/Los_Angeles
encoding: utf-8
safe: true
# theme: src

# This is the text in the top logo. For the value of modifier_class, see
# https://decanter.stanford.edu/component/identity-lockup/

lockup_line2: Marlowe 
lockup_link: /index.html
lockup_line1: Research Computing
lockup_modifier_class: su-lockup--option-b
